package com.jackie.trpc.service;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;

import com.jackie.trpc.service.TrpcDemo.ProcessDataRequest;
import com.jackie.trpc.service.TrpcDemo.mydata;

/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "trpc.test.helloworld.DataService")
public interface DataServiceAsyncAPI {

    /**
     * ProcessData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link mydata}
     */
    @TRpcMethod(name = "ProcessData")
    CompletionStage<mydata> processData(RpcContext context, ProcessDataRequest request);
}